#!/usr/bin/env php

<?php

require 'src/bootstrap.php';

use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new Socapi\Commands\LFPImport());
$application->add(new Socapi\Commands\LFPImportPlayers());
$application->run();